// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtmrsmbjllrfmduztofj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10bXJzbWJqbGxyZm1kdXp0b2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTU1ODgsImV4cCI6MjA3Mzc5MTU4OH0.4ZqBEeb0Q4hImYot3ov9ZxHcb-X2bB6v4TF5i4wJ0QQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});